version: "3.8"

services:
  latex-sandbox:
    build:
      context: ./packages/latex-sandbox
    container_name: latex-sandbox
    ports:
      - "8080:8080"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp

networks:
  latex-net:
    driver: bridge
